### ISSUE TITLE
assert.h not found

### ISSUE THREAD

**Issue by ViralBShah** [staticfloat/OpenlibmBuilder#1]
Not sure what to do about this:

https://travis-ci.org/JuliaMath/OpenlibmBuilder/builds/471701857

```
src/e_j0.c:14:10: fatal error: 'assert.h' file not found
#include <assert.h>
         ^~~~~~~~~~
1 error generated.
make: *** [Make.inc:136: src/e_j0.c.o] Error 1
make: *** Waiting for unfinished jobs....
ERROR: LoadError: Build for Openlibm on x86_64-apple-darwin14-gcc4 did not complete successfully
```

cc @staticfloat

**Comment by ViralBShah** [comment]
@staticfloat @Keno Any ideas how to fix?

**Comment by staticfloat** [comment]
It's because Openlibm is being really forceful in its setting of `CC` and `CFLAGS` and such.  We're not really following standard guidelines in openlibm, so it doesn't "just work" with our BB setup.  See https://github.com/JuliaMath/OpenlibmBuilder/pull/2 for a fix.

**Comment by ViralBShah** [comment]
Thanks that worked.

**Comment by ViralBShah** [comment]
The built files did not get uploaded. What does this mean:

```
Skipping a deployment with the releases provider because this is not a tagged commit
```

**Comment by ViralBShah** [comment]
I thought the commit was tagged v0.6.0.

**Comment by ararslan** [comment]
No, it appears 0.6.0 was tagged from an older revision; GitHub shows 7 commits committed to master since the tag: https://github.com/JuliaMath/OpenlibmBuilder/compare/v0.6.0...master.
